/*
 * Copyright (c) 2025 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#ifndef OHOS_FORM_FWK_FORM_CONSTANTS_FUZZER_H
#define OHOS_FORM_FWK_FORM_CONSTANTS_FUZZER_H

namespace OHOS {
namespace FuzzerConstants {
constexpr long long TOKEN_ID = 718336240uLL;
constexpr long long OFFSET = 32;

constexpr int8_t NUMBER_0 = 0;
constexpr int8_t NUMBER_1 = 1;
constexpr int8_t NUMBER_2 = 2;
constexpr int8_t NUMBER_3 = 3;
constexpr int8_t NUMBER_16 = 16;
constexpr int8_t NUMBER_32 = 32;
constexpr int8_t NUMBER_64 = 64;
constexpr int16_t NUMBER_128 = 128;
constexpr int16_t NUMBER_256 = 256;

enum IpcType : int8_t {
    TYPE_HOST = 0,
    TYPE_PROVIDER = 1,
    TYPE_OBSERVER = 2,
    TYPE_OTHER = 3
};

enum IpcCode : int16_t {
    ADD_FORM = 3001,
    DELETE_FORM = 3003,
    UPDATE_FORM = 3004,
    LIFECYCLE_UPDATE = 3005,
    REQUEST_FORM = 3006,
    RELEASE_FORM = 3007,
    CAST_TEMP_FORM = 3009,
    SET_NEXT_REFRESH_TIME = 3012,
    NOTIFY_FORM_WHETHER_VISIBLE = 3013,
    STORAGE_FORM_INFOS = 3014,
    FORM_INFOS_BY_NAME = 3015,
    FORM_INFOS_BY_ID = 3016,
    FORM_TIMER_INFO_BY_ID = 3017,
    MESSAGE_EVENT = 3018,
    DELETE_INVALID_FORMS = 3023,
    ACQUIRE_FORM_STATE = 3024,
    NOTIFY_FORMS_VISIBLE = 3025,
    NOTIFY_FORMS_ENABLE_UPDATE = 3026,
    GET_ALL_FORMS_INFO = 3027,
    GET_FORMS_INFO_BY_APP = 3028,
    GET_FORMS_INFO_BY_MODULE = 3029,
    GET_FORMS_INFO = 3030,
    ROUTER_EVENT = 3031,
    REQUEST_PUBLISH_FORM = 3035,
    IS_REQUEST_PUBLISH_FORM_SUPPORTED = 3036,
    SHARE_FORM = 3037,
    RECV_FORM_SHARE_INFO_FROM_REMOTE = 3038,
    START_ABILITY = 3039,
    NOTIFY_FORMS_PRIVACY_PROTECTED = 3040,
    CHECK_FMS_READY = 3041,
    BACKGROUND_EVENT = 3042,
    STOP_RENDERING_FORM = 3043,
    REGISTER_FORM_ADD_OBSERVER_BY_BUNDLE = 3044,
    REGISTER_FORM_REMOVE_OBSERVER_BY_BUNDLE = 3045,
    ACQUIRE_DATA = 3046,
    GET_FORMS_COUNT = 3047,
    GET_HOST_FORMS_COUNT = 3048,
    GET_RUNNING_FORM_INFOS = 3049,
    GET_RUNNING_FORM_INFOS_BY_BUNDLE = 3050,
    GET_FORM_INSTANCES_BY_FILTER = 3051,
    GET_FORM_INSTANCES_BY_ID = 3052,
    REGISTER_ADD_OBSERVER = 3053,
    REGISTER_REMOVE_OBSERVER = 3054,
    UPDATE_PROXY_FORM = 3055,
    REQUEST_PUBLISH_PROXY_FORM = 3056,
    RELEASE_RENDERER = 3057,
    REGISTER_PUBLISH_FORM_INTERCEPTOR = 3058,
    UNREGISTER_PUBLISH_FORM_INTERCEPTOR = 3059,
    REGISTER_CLICK_EVENT_OBSERVER = 3060,
    UNREGISTER_CLICK_EVENT_OBSERVER = 3061,
    REGISTER_FORM_ROUTER_PROXY = 3062,
    UNREGISTER_FORM_ROUTER_PROXY = 3063,
    SET_FORMS_RECYCLABLE = 3064,
    RECYCLE_FORMS = 3065,
    RECOVER_FORMS = 3066,
    HAS_FORM_VISIBLE_WITH_TOKENID = 3067,
    UPDATE_FORM_LOCATION = 3068,
    GET_FORMS_INFO_BY_FILTER = 3069,
    CREATE_FORM = 3070,
    SET_PUBLISH_FORM_RESULT = 3071,
    ACQUIRE_ADD_FORM_RESULT = 3072,
    REQUEST_PUBLISH_FORM_WITH_SNAPSHOT = 3073,
    BATCH_REFRESH_FORMS = 3074,
    ENABLE_FORMS = 3075,
    IS_SYSTEM_APP_FORM = 3076,
    IS_FORM_BUNDLE_FORBIDDEN = 3077,
    UPDATE_FORM_SIZE = 3078,
    LOCK_FORMS = 3079,
    IS_FORM_BUNDLE_PROTECTED = 3080,
    IS_FORM_BUNDLE_EXEMPT = 3081,
    NOTIFY_FORM_LOCKED = 3082,
    START_ABILITY_BY_FMS = 3083,
    START_ABILITY_BY_CROSS_BUNDLE = 3084,
    GET_PUBLISHED_FORM_INFOS = 3085,
    GET_PUBLISHED_FORM_INFO_BY_ID = 3086,
    OPEN_FORM_EDIT_ABILITY = 3087,
    REGISTER_OVERFLOW_PROXY = 3088,
    UNREGISTER_OVERFLOW_PROXY = 3089,
    REQUEST_OVERFLOW = 3090,
    REGISTER_CHANGE_SCENEANIMATION_STATE_PROXY = 3091,
    UNREGISTER_CHANGE_SCENEANIMATION_STATE_PROXY = 3092,
    CHANGE_SCENE_ANIMATION_STATE = 3093,
    REGISTER_GET_FORM_RECT = 3094,
    UNREGISTER_GET_FORM_RECT = 3095,
    GET_FORM_RECT = 3096,
    NOTIFY_UPDATE_FORM_SIZE = 3097,
    REGISTER_GET_LIVE_FORM_STATUS = 3098,
    UNREGISTER_GET_LIVE_FORM_STATUS = 3099,
    IS_FORM_BUNDLE_DEBUG_SIGNATURE = 3100,
    RELOAD_FORMS = 3101,
    RELOAD_ALL_FORMS = 3102,
    IS_FORM_DUE_CONTROL = 3103,
    SEND_NON_TRANSPARENT_RATIO = 3104,
    GET_ALL_TEMPLATE_FORMS_INFO = 3105,
    GET_TEMPLATE_FORMS_INFO_BY_APP = 3106,
    GET_TEMPLATE_FORMS_INFO_BY_MODULE = 3107,
};

static const int16_t OTHER_IPC_DODES[] = {
    ACQUIRE_ADD_FORM_RESULT, HAS_FORM_VISIBLE_WITH_TOKENID, STORAGE_FORM_INFOS, FORM_INFOS_BY_NAME,
    FORM_TIMER_INFO_BY_ID, ROUTER_EVENT, BACKGROUND_EVENT, START_ABILITY, RECV_FORM_SHARE_INFO_FROM_REMOTE,
    IS_SYSTEM_APP_FORM, GET_FORMS_COUNT, GET_HOST_FORMS_COUNT, REGISTER_ADD_OBSERVER, REGISTER_REMOVE_OBSERVER,
    UPDATE_PROXY_FORM, REQUEST_PUBLISH_PROXY_FORM, REGISTER_PUBLISH_FORM_INTERCEPTOR, REGISTER_CLICK_EVENT_OBSERVER,
    UNREGISTER_PUBLISH_FORM_INTERCEPTOR, LOCK_FORMS, UNREGISTER_CLICK_EVENT_OBSERVER,
    REQUEST_PUBLISH_FORM_WITH_SNAPSHOT, BATCH_REFRESH_FORMS, ENABLE_FORMS,
    FORM_INFOS_BY_ID, IS_FORM_BUNDLE_DEBUG_SIGNATURE,
};

static const int16_t OBSERVER_IPC_DODES[] = {
    REGISTER_FORM_ADD_OBSERVER_BY_BUNDLE, REGISTER_FORM_REMOVE_OBSERVER_BY_BUNDLE, GET_RUNNING_FORM_INFOS_BY_BUNDLE,
    GET_RUNNING_FORM_INFOS, GET_FORM_INSTANCES_BY_FILTER, GET_FORM_INSTANCES_BY_ID
};

static const int16_t HOST_IPC_DODES[] = {
    CREATE_FORM, DELETE_FORM, RELEASE_FORM, REQUEST_FORM, CAST_TEMP_FORM, NOTIFY_FORM_WHETHER_VISIBLE, LIFECYCLE_UPDATE,
    CHECK_FMS_READY, DELETE_INVALID_FORMS, ACQUIRE_FORM_STATE, REGISTER_FORM_ROUTER_PROXY, UNREGISTER_FORM_ROUTER_PROXY,
    NOTIFY_FORMS_VISIBLE, NOTIFY_FORMS_ENABLE_UPDATE, GET_ALL_FORMS_INFO, GET_ALL_TEMPLATE_FORMS_INFO,
    GET_FORMS_INFO_BY_FILTER, GET_FORMS_INFO_BY_APP, GET_FORMS_INFO_BY_MODULE, GET_TEMPLATE_FORMS_INFO_BY_APP,
    GET_TEMPLATE_FORMS_INFO_BY_MODULE, SHARE_FORM, ACQUIRE_DATA, NOTIFY_FORMS_PRIVACY_PROTECTED, SET_FORMS_RECYCLABLE,
    RECOVER_FORMS, RECYCLE_FORMS, NOTIFY_FORM_LOCKED, UPDATE_FORM_LOCATION, SET_PUBLISH_FORM_RESULT,
    UNREGISTER_OVERFLOW_PROXY, REGISTER_CHANGE_SCENEANIMATION_STATE_PROXY, REGISTER_GET_FORM_RECT,
    REGISTER_GET_LIVE_FORM_STATUS, UPDATE_FORM_SIZE, UNREGISTER_CHANGE_SCENEANIMATION_STATE_PROXY,
    UNREGISTER_GET_FORM_RECT, REGISTER_OVERFLOW_PROXY, UNREGISTER_GET_LIVE_FORM_STATUS, NOTIFY_UPDATE_FORM_SIZE,
    IS_FORM_BUNDLE_FORBIDDEN, IS_FORM_BUNDLE_PROTECTED, IS_FORM_BUNDLE_EXEMPT, STOP_RENDERING_FORM,
    RELEASE_RENDERER, ADD_FORM, IS_FORM_DUE_CONTROL, SEND_NON_TRANSPARENT_RATIO, MESSAGE_EVENT,
};

static const int16_t PROVIDER_IPC_DODES[] = {
    GET_FORMS_INFO, GET_PUBLISHED_FORM_INFO_BY_ID, GET_PUBLISHED_FORM_INFOS, START_ABILITY_BY_FMS,
    START_ABILITY_BY_CROSS_BUNDLE, SET_NEXT_REFRESH_TIME, UPDATE_FORM, IS_REQUEST_PUBLISH_FORM_SUPPORTED,
    REQUEST_PUBLISH_FORM, OPEN_FORM_EDIT_ABILITY, REQUEST_OVERFLOW, CHANGE_SCENE_ANIMATION_STATE,
    GET_FORM_RECT, RELOAD_FORMS, RELOAD_ALL_FORMS
};
}
}

#endif  // OHOS_FORM_FWK_FORM_CONSTANTS_FUZZER_H

