/*
 * Copyright (c) 2022-2023 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#ifndef OHOS_FORM_FWK_FORM_MGR_ERRORS_H
#define OHOS_FORM_FWK_FORM_MGR_ERRORS_H

#include "errors.h"

namespace OHOS {
namespace {
    const unsigned int AAFWK_MODULE_FORMMGR = 0x03;
    // offset of aafwk error, only be used in this file.
    constexpr ErrCode AAFWK_FORMMGR_ERR_OFFSET = ErrCodeOffset(SUBSYS_AAFWK, AAFWK_MODULE_FORMMGR);
};

// Internal Error Code
enum {
    ERR_APPEXECFWK_FORM_COMMON_CODE = AAFWK_FORMMGR_ERR_OFFSET + 1, // 2293761
    ERR_APPEXECFWK_FORM_PERMISSION_DENY,
    ERR_APPEXECFWK_FORM_PERMISSION_DENY_BUNDLE,
    ERR_APPEXECFWK_FORM_PERMISSION_DENY_SYS,
    ERR_APPEXECFWK_FORM_GET_INFO_FAILED,
    ERR_APPEXECFWK_FORM_GET_BUNDLE_FAILED,
    ERR_APPEXECFWK_FORM_INVALID_PARAM,
    ERR_APPEXECFWK_FORM_INVALID_FORM_ID,
    ERR_APPEXECFWK_FORM_FORM_ID_NUM_ERR,
    ERR_APPEXECFWK_FORM_FORM_ARRAY_ERR,
    ERR_APPEXECFWK_FORM_RELEASE_FLG_ERR,
    ERR_APPEXECFWK_FORM_REFRESH_TIME_NUM_ERR,
    ERR_APPEXECFWK_FORM_INVALID_BUNDLENAME,
    ERR_APPEXECFWK_FORM_INVALID_MODULENAME,
    ERR_APPEXECFWK_FORM_INVALID_PROVIDER_DATA,
    ERR_APPEXECFWK_FORM_INVALID_REFRESH_TIME,
    ERR_APPEXECFWK_FORM_FORM_ID_ARRAY_ERR,
    ERR_APPEXECFWK_FORM_SERVER_STATUS_ERR,
    ERR_APPEXECFWK_FORM_CFG_NOT_MATCH_ID,
    ERR_APPEXECFWK_FORM_NOT_EXIST_ID,
    ERR_APPEXECFWK_FORM_PROVIDER_DATA_EMPTY,
    ERR_APPEXECFWK_FORM_BIND_PROVIDER_FAILED,
    ERR_APPEXECFWK_FORM_MAX_SYSTEM_FORMS,
    ERR_APPEXECFWK_FORM_EXCEED_INSTANCES_PER_FORM,
    ERR_APPEXECFWK_FORM_OPERATION_NOT_SELF,
    ERR_APPEXECFWK_FORM_PROVIDER_DEL_FAIL,
    ERR_APPEXECFWK_FORM_MAX_FORMS_PER_CLIENT,
    ERR_APPEXECFWK_FORM_MAX_SYSTEM_TEMP_FORMS,
    ERR_APPEXECFWK_FORM_NO_SUCH_MODULE,
    ERR_APPEXECFWK_FORM_NO_SUCH_ABILITY,
    ERR_APPEXECFWK_FORM_NO_SUCH_DIMENSION,
    ERR_APPEXECFWK_FORM_FA_NOT_INSTALLED,
    ERR_APPEXECFWK_FORM_MAX_REQUEST,
    ERR_APPEXECFWK_FORM_MAX_REFRESH,
    ERR_APPEXECFWK_FORM_GET_BMS_FAILED,
    ERR_APPEXECFWK_FORM_GET_AMSCONNECT_FAILED,
    ERR_APPEXECFWK_FORM_GET_HOST_FAILED,
    // error code in sdk
    ERR_APPEXECFWK_FORM_GET_FMS_FAILED,
    ERR_APPEXECFWK_FORM_SEND_FMS_MSG,
    ERR_APPEXECFWK_FORM_FORM_DUPLICATE_ADDED,
    ERR_APPEXECFWK_FORM_IN_RECOVER,
    ERR_APPEXECFWK_FORM_GET_SYSMGR_FAILED,
    ERR_APPEXECFWK_FORM_SHARE_INFO_CHECK_FAILED,
    ERR_APPEXECFWK_FORM_SHARING,
    ERR_APPEXECFWK_FORM_FREE_INSTALL_TIMEOUT,
    ERR_APPEXECFWK_FORM_START_FORM_USER_FAILED,
    ERR_APPEXECFWK_FORM_FREE_INSTALL_FAILED,
    ERR_APPEXECFWK_FORM_FREE_INSTALLATION,
    ERR_APPEXECFWK_FORM_GET_DMS_PROXY_FAILED,
    ERR_APPEXECFWK_FORM_DISTRIBUTED_SCHEDULE_FAILED,
    ERR_APPEXECFWK_FORM_FORM_USER_NOT_EXIST,
    ERR_APPEXECFWK_FORM_CONNECT_FORM_RENDER_FAILED,
    ERR_APPEXECFWK_FORM_RENDER_SERVICE_DIED,
    ERR_APPEXECFWK_FORM_NOT_TRUST,
    ERR_APPEXECFWK_FORM_SHARING_MAX_SIZE,
    ERR_APPEXECFWK_FORM_ADD_FORM_TIME_OUT,
    ERR_APPEXECFWK_FORM_STATUS_TIMIE_OUT,
    // error code in enable or disable form
    ERR_APPEXECFWK_FORM_DISABLE_REFRESH,
    ERR_APPEXECFWK_FORM_REPEAT_DISABLE,
    ERR_APPEXECFWK_FORM_RDB_REPEATED_BUILD,
    ERR_APPEXECFWK_FORM_GET_APP_DISPOSED_STATUS_FAILED,
    ERR_APPEXECFWK_FORM_SET_OPERATION_FAILED,
    ERR_APPEXECFWK_FORM_LIVE_OP_UNSUPPORTED,
    ERR_APPEXECFWK_SYSTEMCAP_ERROR,
    ERR_APPEXECFWK_FORM_DIMENSION_ERROR,
    // error code in form render service
    ERR_APPEXECFWK_FORM_EVENT_HANDLER_NULL,
    ERR_APPEXECFWK_FORM_NOT_EXIST_RENDER_RECORD,
    ERR_APPEXECFWK_FORM_NOT_EXIST_FORM_REQUEST,
    ERR_APPEXECFWK_FORM_RUNTIME_FAILED,
    ERR_APPEXECFWK_FORM_FORM_NODE_RELEASED,
    ERR_APPEXECFWK_FORM_UICONTENT_INIT_FAILED,
    ERR_APPEXECFWK_FORM_SURFACE_NODE_NOT_FOUND,
    ERR_APPEXECFWK_FORM_SUPPLY_CLIENT_NULL,
    ERR_APPEXECFWK_FORM_NOT_EXIST_RENDERER_GROUP,
    ERR_APPEXECFWK_FORM_LIVE_OP_PAGE_INFO_MISTMATCH,
};

// External Error Code
enum {
    ERR_FORM_EXTERNAL_PERMISSION_DENIED = 201,
    ERR_FORM_EXTERNAL_NOT_SYSTEM_APP = 202,
    ERR_FORM_EXTERNAL_PARAM_INVALID = 401,
    ERR_FORM_EXTERNAL_SYSTEMCAP_ERROR = 801,
    ERR_FORM_EXTERNAL_KERNEL_ERROR = 16500001,
    ERR_FORM_EXTERNAL_KERNEL_MALLOC_ERROR = 16500002,
    ERR_FORM_EXTERNAL_IPC_ERROR = 16500050,
    ERR_FORM_EXTERNAL_SERVICE_CONNECTION_ERROR = 16500060,
    ERR_FORM_EXTERNAL_GET_INFO_FAILED = 16500100,
    ERR_FORM_EXTERNAL_FUNCTIONAL_ERROR = 16501000,
    ERR_FORM_EXTERNAL_FORM_ID_NOT_EXIST = 16501001,
    ERR_FORM_EXTERNAL_FORM_NUM_EXCEEDS_UPPER_BOUND = 16501002,
    ERR_FORM_EXTERNAL_OPERATION_FORM_NOT_SELF = 16501003,
    ERR_FORM_EXTERNAL_ABILITY_NOT_INSTALLED = 16501004,
    ERR_FORM_EXTERNAL_CONNECT_RENDER_FAILED = 16501005,
    ERR_FORM_EXTERNAL_RENDER_DIED = 16501006,
    ERR_FORM_EXTERNAL_FORM_NOT_TRUST = 16501007,
    ERR_FORM_EXTERNAL_ADD_FORM_TIME_OUT = 16501008,
    ERR_FORM_EXTERNAL_FORM_STATUS_TIMIE_OUT = 16501009,
    ERR_FORM_EXTERNAL_SET_OPERATION_FAILED = 16501010,
    ERR_FORM_EXTERNAL_LIVE_OP_UNSUPPORTED = 16501011,
    ERR_FORM_EXTERNAL_FORM_DIMENSION_ERROR = 16501012,
};
}  // namespace OHOS
#endif  // OHOS_FORM_FWK_FORM_MGR_ERRORS_H
