/*
 * Copyright (c) 2025 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * limitations under the License.
 */
 
sequenceable OHOS.AAFwk.Want;
sequenceable FormInstance..OHOS.AppExecFwk.OverflowInfo;
sequenceable FormInstance..OHOS.AppExecFwk.Rect;
sequenceable OHOS.AppExecFwk.TemplateFormDetailInfo;

interface OHOS.AppExecFwk.IFormHostDelegate {
    [ipccode 4002] void RouterEvent([in] long formId, [in] Want want);
    [ipccode 4003] void RequestOverflow([in] long formId, [in] OverflowInfo overflowInfo, [in] boolean isOverflow);
    [ipccode 4004] void ChangeSceneAnimationState([in] long formId, [in] int state);
    [ipccode 4005] void GetFormRect([in] long formId, [inout] Rect rect);
    [ipccode 4006] void GetLiveFormStatus([inout] Map<String, String> liveFormStatusMap);
    [ipccode 4007] void TemplateFormDetailInfoChange([in] TemplateFormDetailInfo[] templateFormDetailInfo);
}