/*
 * Copyright (c) 2025 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * limitations under the License.
 */
 
sequenceable FormInstance..OHOS.AppExecFwk.PublishFormCrossBundleInfo;

interface OHOS.AppExecFwk.IFormProviderDelegate {
    [ipccode 4201] void PublishFormCrossBundleControl([in] PublishFormCrossBundleInfo bundleInfo, [inout] boolean isCanOpen);
}